name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update snake animation
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: OtavioValeDev
          outputs: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
